set BCC32PATH="D:\Program Files (x86)\CodeGear\RAD Studio\5.0\bin\bcc32.exe"

%BCC32PATH% -c -n..\  jdapimin.c
%BCC32PATH% -c -n..\  jmemmgr.c
%BCC32PATH% -c -n..\  jmemnobs.c
%BCC32PATH% -c -n..\  jdinput.c
%BCC32PATH% -c -n..\  jdatasrc.c
%BCC32PATH% -c -n..\  jdapistd.c
%BCC32PATH% -c -n..\  jdmaster.c
%BCC32PATH% -c -n..\  jdphuff.c
%BCC32PATH% -c -n..\  jdhuff.c
%BCC32PATH% -c -n..\  jdmerge.c
%BCC32PATH% -c -n..\  jdcolor.c
%BCC32PATH% -c -n..\  jquant1.c
%BCC32PATH% -c -n..\  jquant2.c
%BCC32PATH% -c -n..\  jdmainct.c
%BCC32PATH% -c -n..\  jdcoefct.c
%BCC32PATH% -c -n..\  jdpostct.c
%BCC32PATH% -c -n..\  jddctmgr.c
%BCC32PATH% -c -n..\  jdsample.c
%BCC32PATH% -c -n..\  jidctflt.c
%BCC32PATH% -c -n..\  jidctfst.c
%BCC32PATH% -c -n..\  jidctint.c
%BCC32PATH% -c -n..\  jidctred.c
%BCC32PATH% -c -n..\  jdmarker.c
%BCC32PATH% -c -n..\  jutils.c
%BCC32PATH% -c -n..\  jcomapi.c
%BCC32PATH% -c -n..\  jdatadst.c
%BCC32PATH% -c -n..\  jcparam.c
%BCC32PATH% -c -n..\  jcapistd.c
%BCC32PATH% -c -n..\  jcapimin.c
%BCC32PATH% -c -n..\  jcinit.c
%BCC32PATH% -c -n..\  jcmarker.c
%BCC32PATH% -c -n..\  jcmaster.c
%BCC32PATH% -c -n..\  jcmainct.c
%BCC32PATH% -c -n..\  jcprepct.c
%BCC32PATH% -c -n..\  jccoefct.c
%BCC32PATH% -c -n..\  jccolor.c
%BCC32PATH% -c -n..\  jcsample.c
%BCC32PATH% -c -n..\  jcdctmgr.c
%BCC32PATH% -c -n..\  jcphuff.c
%BCC32PATH% -c -n..\  jfdctint.c
%BCC32PATH% -c -n..\  jfdctfst.c
%BCC32PATH% -c -n..\  jfdctflt.c
%BCC32PATH% -c -n..\  jchuff.c
